project: 
  type: book
  output-dir: _book
  
book:
  title: "Ding Lab Manual"
  author: "Serena Ding"
  date: last-modified 
  description: "This is the lab manual for the Ding Lab at the Max Planck Institute of Animal Behavior" 
  
  page-footer:
    left: |
      <a href="https://www.serenadinglab.com">The Ding Lab</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://serenadinglab.github.io/lab-manual/
  repo-url: https://github.com/SerenaDingLab/lab-manual
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 02_SOPs.qmd



